version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: niktere/api:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ./.env

  frontend:
    image: niktere/front:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: